# -*- mode: ruby -*-
# vi: set ft=ruby :

# Kerberos KDC
$KDC_SCRIPT = <<EOF
touch /var/log/vagrant-setup.log; \
source /vagrant/config/mongo_config/config.sh | tee -a /var/log/vagrant-setup.log;\
bash /vagrant/config/kerberos/install_kdc.sh         | tee -a /var/log/vagrant-setup.log;
EOF

# Mongod
$MONGOD_SCRIPT = <<EOF
touch /var/log/vagrant-setup.log; \
source /vagrant/config/mongo_config/config.sh | tee -a /var/log/vagrant-setup.log;\
bash /vagrant/config/mongo_config/install.sh  | tee -a /var/log/vagrant-setup.log;\
bash /vagrant/config/kerberos/install_mongod.sh  | tee -a /var/log/vagrant-setup.log;
EOF


Vagrant.configure("2") do |config|
  config.vm.define :kdc do |mongod|
    # pick my own version here
    mongod.vm.box = "CentoOS 6.4"
    mongod.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210-nocm.box"

    mongod.vm.provider "virtualbox" do |v|
       # v.customize ["modifyvm", :id, "--cpus", "1"]
    end

    mongod.vm.network :private_network, ip: "192.168.19.100"
    mongod.vm.hostname = "kdc.mongotest.com"
    mongod.vm.provision :shell, :inline => $KDC_SCRIPT
  end

  config.vm.define :mongod_rh64 do |mongod|
    # pick my own version here
    mongod.vm.box = "CentoOS 6.4"
    mongod.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210-nocm.box"

    mongod.vm.provider "virtualbox" do |v|
       v.customize ["modifyvm", :id, "--cpus", "2"]
    end

    mongod.vm.network :private_network, ip: "192.168.19.101"
    mongod.vm.hostname = "rhel64.mongotest.com"
    mongod.vm.provision :shell, :inline => $MONGOD_SCRIPT
  end  
end
